- hosts: etcd,master,node
  remote_user: root
  gather_facts: no
  roles:
      - allhosts

- hosts: etcd
  remote_user: root
  roles:
       - etcd

- hosts: master,node
  remote_user: root
  gather_facts: no
  tasks:
    - name: 新建工作目录
      file: 
        path: /etc/kubernetes
        state: directory
    - name: 新建日志文件目录
      file: 
        path: /var/log/kubernetes
        state: directory

- hosts: master
  remote_user: root
  roles:
       - apiserver
       - keepalived-haproxy
       - config
       - controller-manager
       - scheduler
       - master-auth

- hosts: node
  remote_user: root
  vars:
    system_version: 7
    containerd_version: "1.2.6-3.3.el7"
  tasks:
    - name: 安装 docker
      yum: name=docker-ce state=present
    - name: 启用 docker
      service: name=docker.service enabled=yes state=started

- hosts: node
  remote_user: root
  roles:
       - flanneld
       - kubelet
       - proxy

